included: # 执行 linting 时包含的路径。如果出现这个 `--path` 会被忽略。
  - AI-in-iOS
excluded: # 执行 linting 时忽略的路径。 优先级比 `included` 更高。
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  
disabled_rules: # 执行时排除掉的规则
  - colon
  - comma
  - control_statement
opt_in_rules: # 一些规则仅仅是可选的
  - empty_count
